### Numpy ###

##### Arreglos #####

###### Importar la libreria ######

In [1]:
import numpy as np

###### Crear arreglo ######

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

###### Almacenar arreglo en una variable ######

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

###### Consultar tipo ######

In [6]:
type(a)

numpy.ndarray

###### Consultar atributos: cantidad de elementos. ######

In [7]:
a.size

5

###### Consultar atributos: cantidad de dimensiones. ######

In [8]:
a.ndim

1

###### Consultar atributos: tipos de datos que almacena. ######

In [9]:
a.dtype

dtype('int64')

###### Consultar atributos: conocer dimensiones y cantidad de elementos. ######

In [10]:
a.shape

(5,)

##### Operaciones #####

###### Sumar, restar, multiplicar y dividir sobre cada uno de los elementos ######

In [18]:
a = np.array([1,2,3,4,5])

In [13]:
a + 10

array([11, 12, 13, 14, 15])

In [14]:
a - 10

array([-9, -8, -7, -6, -5])

In [15]:
a * 10

array([10, 20, 30, 40, 50])

In [16]:
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

###### Sumar dos arreglos ######

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a + b

array([ 7,  9, 11, 13, 15])

##### Tipos de datos #####

In [6]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [18]:
a = np.array([1,2,3,4,5], dtype=float)
a

array([1., 2., 3., 4., 5.])

In [15]:
a = np.array([1,2,3,4,5], dtype=str)
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
a = np.array([1,2,3,4,5], dtype=bool)
a

array([ True,  True,  True,  True,  True])

In [17]:
a = np.array([1,2,3,4,5], dtype=np.complex_)
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

##### Crear arreglos #####

###### Arreglo con n cantidad de elementos ######

In [19]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

###### Opcionalmente un tercer argumento el cual denota la cantidad de saltos a utilizar ######

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Crear arreglo de ceros

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros(10, dtype=int).dtype

dtype('int64')

###### Con 1(unos) ######

In [24]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###### Crear Arreglo con valores basura ######

In [25]:
np.empty(10)

array([ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  6.92810406e-310,  3.42346130e-032,
        4.90482501e-062,  7.42498991e-091,  1.68686412e-051,
       -1.38001728e+196])

In [26]:
np.empty(10, dtype=int)

array([                   0,                    0,                    0,
                          0,      140226387247104,  4136055101164970849,
        3689623894545806125,  3258410612596499554,  3847255202971399524,
       -1682198398138698394])

###### Crear arreglo con numeros enteros aleatorios ######

In [27]:
np.random.randint(0,100,50)

array([62, 13, 74, 76, 37, 41,  6, 20, 14, 35, 46, 18, 80, 70, 65, 79, 74,
       34,  2, 94, 56, 29, 40, 87, 67,  1, 99, 20, 90, 84, 81, 23, 42, 75,
       93, 26, 85, 20, 86,  7, 92, 84, 14, 61, 53, 46, 53, 69, 55, 49])

In [28]:
np.random.randint(0,10,50)

array([4, 3, 4, 3, 8, 0, 7, 1, 1, 7, 5, 6, 4, 8, 0, 1, 2, 3, 5, 5, 4, 4,
       4, 5, 9, 5, 0, 4, 4, 0, 2, 8, 3, 1, 0, 8, 0, 8, 7, 2, 6, 3, 8, 8,
       7, 5, 4, 9, 1, 1])

##### Obtener y actualizar elementos #####

###### Obtener un elemento (indice se cuenta a partir del 0 de izquierda a derecha) ######

In [4]:
a = np.random.randint(0,10,10)
a

array([0, 4, 1, 4, 7, 9, 0, 6, 6, 6])

In [5]:
a[0]

0

###### Si el indice es negativo se lee de derecha a izquierda  ######

In [6]:
a[-1]

6

###### Modificar valor de algun indice ######

In [7]:
a[0] = 100
a[0]

100

##### SubArreglos #####

In [24]:
a = np.random.randint(0,10,20)
a

array([8, 8, 4, 5, 2, 4, 6, 9, 3, 7, 2, 0, 4, 1, 7, 7, 2, 4, 2, 6])

###### a[start:end:saltos] ######

In [25]:
a[0:5]

array([8, 8, 4, 5, 2])

In [26]:
a[:5]

array([8, 8, 4, 5, 2])

In [27]:
a[5:]

array([4, 6, 9, 3, 7, 2, 0, 4, 1, 7, 7, 2, 4, 2, 6])

In [28]:
a[5::2]

array([4, 9, 7, 0, 1, 7, 4, 6])

###### Listado utilizando indices ######

In [32]:
a[ [0,1,3] ]

array([8, 8, 5])

In [35]:
a[ [0, 1, 3, 5, 6] ]

array([8, 8, 5, 4, 6])

###### Obtener elementos con booleanos (debe poseer la misma cantidad de elementos que el arreglo) ######

In [36]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [37]:
b[ [True, False, False, False, True] ]

array([1, 5])

In [38]:
b[ [True, False, True, False, True] ]

array([1, 3, 5])

##### Vectorizar funciones #####

In [39]:
a = np.random.randint(0, 10, 20)
a

array([2, 7, 7, 4, 2, 6, 4, 2, 7, 7, 5, 2, 6, 5, 0, 1, 3, 1, 4, 4])

In [40]:
def operacion(valor):
    return(valor ** 2) + 2

In [41]:
operacion(3)

11

###### Aplicamos la funcion operacion al arreglo (utilizando ciclo for) ######

In [42]:
for valor in a:
    print(operacion(valor))

6
51
51
18
6
38
18
6
51
51
27
6
38
27
2
3
11
3
18
18


###### Generar un nuevo vector a partir de la funcion anterior ######

In [43]:
vector = np.vectorize(operacion)
vector(a)

array([ 6, 51, 51, 18,  6, 38, 18,  6, 51, 51, 27,  6, 38, 27,  2,  3, 11,
        3, 18, 18])

###### Otra manera usando una funcion lambda

In [44]:
vector = np.vectorize(lambda valor: (valor ** 2) + 2)
vector(a)

array([ 6, 51, 51, 18,  6, 38, 18,  6, 51, 51, 27,  6, 38, 27,  2,  3, 11,
        3, 18, 18])

##### Copias y vistas #####

In [2]:
import numpy as np

In [3]:
a = np.arange(0,10)

In [5]:
# arreglo original
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

copy()

In [6]:
a.copy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = a.copy()

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
id(a)

140527974796336

In [10]:
id(b)

140527974795568

In [12]:
a[0] = 100

In [13]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [14]:
b[0] = 200

In [16]:
b

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9])

view()

In [17]:
a.view()

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
c = a.view()

In [19]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
id(c)

140527706650352

In [21]:
id(a)

140527974796336

In [22]:
a is c

False

In [23]:
a[-1] = 150

In [24]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8, 150])

In [25]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8, 150])

In [26]:
c[-2] = 180

In [27]:
c

array([100,   1,   2,   3,   4,   5,   6,   7, 180, 150])

In [28]:
a

array([100,   1,   2,   3,   4,   5,   6,   7, 180, 150])

In [29]:
c.base

array([100,   1,   2,   3,   4,   5,   6,   7, 180, 150])

In [30]:
id(a)

140527974796336

In [31]:
id(c.base)

140527974796336

[:]

In [32]:
d = a[:]

In [33]:
d

array([100,   1,   2,   3,   4,   5,   6,   7, 180, 150])

In [34]:
d.base is a

True

Matrices

In [37]:
import numpy as np

In [38]:
a = np.array([
    [1,2,3,4,5],
    [10,20,30,40,50],
    [100,200,300,400,500]
])

In [39]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [40]:
a.ndim

2

In [41]:
a.shape

(3, 5)

In [47]:
# Axi0 = Filas
# Axi1 = Columnas

# a[axi0][axi1]

In [44]:
a[0][0]

1

In [45]:
a[1][2]

30

In [46]:
a[2][4]

500

Otra manera

In [48]:
a[0,0]

1

In [49]:
a[1,2]

30

In [50]:
a[2,4]

500

In [51]:
a[1, :3]

array([10, 20, 30])

In [52]:
a[2, 2:]

array([300, 400, 500])

In [53]:
a[0, [0, 4]]

array([1, 5])

In [54]:
a[:, 3]

array([  4,  40, 400])

In [55]:
a[[0,2], 3]

array([  4, 400])

Metodos de agregacion

In [64]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [57]:
# desviacion estandar del arreglo
a.std()

157.21323099535866

In [58]:
# suma total de todos los elementos del arreglo
a.sum()

1665

In [59]:
a.min()

1

In [60]:
a.max()

500

In [61]:
a.mean()

111.0

In [62]:
a[1]

array([10, 20, 30, 40, 50])

In [63]:
a[1].sum()

150

In [65]:
a[2].min()

100

In [66]:
a[2].max()

500

In [69]:
a[:, 4]

array([  5,  50, 500])

In [70]:
a[:, 4].mean()

185.0

Transposicion

In [71]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [76]:
a.shape

(3, 5)

In [73]:
a[:, 4].sum()

555

In [72]:
a.T

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500]])

In [75]:
a.T.shape

(5, 3)

In [74]:
a.T[4].sum()

555

Filtros y condiciones

In [77]:
a = np.random.randint(0, 100, 50)

In [78]:
a

array([21, 60, 86, 78, 99, 78, 73, 86, 28, 29, 34, 33, 81, 82, 94, 68, 96,
       58,  3, 87, 97, 72, 49,  7, 25, 83,  1, 65, 67, 40, 25, 15, 71, 19,
       47, 72, 18, 18, 41, 89, 48, 31, 86, 73,  6, 40, 77, 92, 31, 37])

In [79]:
a > 50

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True, False,
        True,  True, False, False, False,  True, False, False,  True,
       False, False, False,  True, False, False,  True,  True, False,
       False,  True,  True, False, False])

In [80]:
a[a > 50]

array([60, 86, 78, 99, 78, 73, 86, 81, 82, 94, 68, 96, 58, 87, 97, 72, 83,
       65, 67, 71, 72, 89, 86, 73, 77, 92])

In [81]:
a[a <= 50]

array([21, 28, 29, 34, 33,  3, 49,  7, 25,  1, 40, 25, 15, 19, 47, 18, 18,
       41, 48, 31,  6, 40, 31, 37])

In [82]:
a[(a > 50) & (a <  90)]

array([60, 86, 78, 78, 73, 86, 81, 82, 68, 58, 87, 72, 83, 65, 67, 71, 72,
       89, 86, 73, 77])

In [83]:
a[(a == 10) | (a == 20) | (a == 50)]

array([], dtype=int64)

Condiciones

In [84]:
a

array([21, 60, 86, 78, 99, 78, 73, 86, 28, 29, 34, 33, 81, 82, 94, 68, 96,
       58,  3, 87, 97, 72, 49,  7, 25, 83,  1, 65, 67, 40, 25, 15, 71, 19,
       47, 72, 18, 18, 41, 89, 48, 31, 86, 73,  6, 40, 77, 92, 31, 37])

In [86]:
# si todos los elemetos son mayores a 50
np.all(a > 50)

False

In [87]:
np.any((a >= 0) & (a <=100))

True

In [88]:
np.any(a > 10)

True

In [89]:
np.any(a > 200)

False

Funciones Where y Select

In [90]:
calificaciones = np.random.randint(1, 11, 10)

In [91]:
calificaciones

array([ 6,  4, 10,  8,  8, 10,  7, 10,  6,  6])

In [92]:
# todas las calificaciones mayores a 7 son aprobatorias
# dos tipos de mensajes
# felicidades, aprobaste la materia
# lo sentimos, no aprobaste la materia

In [93]:
np.where(
    calificaciones >= 7,
    'Felicidades, aprobaste la materia',
    'Lo sentimos, no aprobaste la materia')

array(['Lo sentimos, no aprobaste la materia',
       'Lo sentimos, no aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Lo sentimos, no aprobaste la materia',
       'Lo sentimos, no aprobaste la materia'], dtype='<U36')

In [94]:
# 4 tipos de mensajes
# Felicidades, aprobaste la materia con 10 = 10
# Felicidades, aprobaste la materia = 8 o 9
# Aprobaste la materia = 7
# Lo sentimos, no aprobaste la materia = menor que 7

In [95]:
condiciones = [
    (calificaciones == 100),
    ((calificaciones  == 8) | (calificaciones == 9)),
    (calificaciones == 7),
    (calificaciones < 7)
]

In [96]:
opciones = [
    'Felicidades, aprobaste la materia con 10',
    'Felicidades, aprobaste la materia',
    'Aprobaste la materia',
    'Lo sentimos, no aprobaste la materia'
]

In [97]:
np.select(condiciones, opciones)

array(['Lo sentimos, no aprobaste la materia',
       'Lo sentimos, no aprobaste la materia', '0',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia', '0', 'Aprobaste la materia',
       '0', 'Lo sentimos, no aprobaste la materia',
       'Lo sentimos, no aprobaste la materia'], dtype='<U40')

Crear y leer archivos pt1

In [98]:
a = np.random.randint(0, 10, 10)

In [99]:
a

array([9, 2, 8, 7, 3, 0, 9, 8, 2, 1])

In [100]:
# se almacenan por defecto complex
np.savetxt('arreglo.txt', a)

In [101]:
np.savetxt('arreglo.txt', a, fmt='%i')

In [103]:
b = np.loadtxt('arreglo.txt')

In [104]:
b

array([9., 2., 8., 7., 3., 0., 9., 8., 2., 1.])

In [106]:
b.dtype

dtype('float64')

In [107]:
b = np.loadtxt('arreglo.txt', dtype=int)

In [108]:
b

array([9, 2, 8, 7, 3, 0, 9, 8, 2, 1])

In [109]:
a.reshape((2,5))

array([[9, 2, 8, 7, 3],
       [0, 9, 8, 2, 1]])

In [111]:
c = a.reshape((2,5))

In [112]:
# por defecto formato complex
np.savetxt('matriz.csv', c, delimiter=',')

In [113]:
np.savetxt('matriz.csv', c, delimiter=',', fmt='%i')

Crear y leer archivos pt2

In [114]:
a

array([9, 2, 8, 7, 3, 0, 9, 8, 2, 1])

In [115]:
np.save('arreglo_binario.npy', a)

In [116]:
b = np.load('arreglo_binario.npy')

In [117]:
b

array([9, 2, 8, 7, 3, 0, 9, 8, 2, 1])

Modificar arreglos

In [119]:
a = np.random.randint(0, 10, 10)

In [120]:
a

array([4, 7, 8, 5, 8, 8, 9, 1, 0, 2])

In [121]:
a.size

10

In [122]:
np.insert(a, 0, 200)

array([200,   4,   7,   8,   5,   8,   8,   9,   1,   0,   2])

In [123]:
a = np.append(a, 200)

In [124]:
a

array([  4,   7,   8,   5,   8,   8,   9,   1,   0,   2, 200])

In [125]:
np.delete(a, -1)

array([4, 7, 8, 5, 8, 8, 9, 1, 0, 2])

In [126]:
b = np.array([10,20,30,40,50])

In [127]:
b

array([10, 20, 30, 40, 50])

In [128]:
a

array([  4,   7,   8,   5,   8,   8,   9,   1,   0,   2, 200])

In [129]:
np.concatenate([a,b])

array([  4,   7,   8,   5,   8,   8,   9,   1,   0,   2, 200,  10,  20,
        30,  40,  50])

Ordenamiento

In [130]:
a = np.random.randint(0, 10, 20)

In [131]:
a

array([7, 8, 1, 7, 6, 9, 8, 6, 5, 7, 8, 8, 6, 4, 1, 0, 8, 6, 0, 0])

In [132]:
a.sort()

In [133]:
a

array([0, 0, 0, 1, 1, 4, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 9])

In [134]:
a[::-1]

array([9, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 4, 1, 1, 0, 0, 0])

In [135]:
a

array([0, 0, 0, 1, 1, 4, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 9])